network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 172.30.29.136/24
      routes:
        - to: default
          via: 172.30.29.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4