network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 172.19.112.10/20
      gateway4: 172.19.112.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
